### ISSUE TITLE
Subject: Implement time filter/zoom

### ISSUE THREAD

**Issue by petcupaula** [RADAR-base/RADAR-Dashboard#124]
Implement time filter/zoom based on the sketch mockups for patient view.

Also, we will have event markers for some of the data (start and stop datetimestamp for tasks performed during visits), so we need to think how to represent these.

**Comment by herkulano** [comment]
Latest design of the Patient view:

![desktop 400-patient](https://cloud.githubusercontent.com/assets/125300/23798352/f065b572-05ac-11e7-942b-f4bb664e20f5.png)

![desktop 401-patient](https://cloud.githubusercontent.com/assets/125300/23798353/f066a4d2-05ac-11e7-8e84-a3d4c5647546.png)

https://github.com/RADAR-CNS/RADAR-Design/tree/master/_Output/Screens

**Comment by mpgxvii** [comment]
Solved in #314 #316 #317
