### ISSUE TITLE
Subject: Chart tooltip, axis labels, and legend

### ISSUE THREAD

**Issue by petcupaula** [RADAR-base/RADAR-Dashboard#87]
- [x] Show tooltip with actual value on mouse-over (maybe also show a vertical line)
- [x] Show labels on axis (for example: on vertical axis average bpm and on horizontal axis datetime)
- [x] Add legend (will be useful especially for multi line chart or for categorical data shown in a bar chart)

**Comment by mpgxvii** [comment]
Solved  in #321, #325, #247, #248
